use database ah_raw;
use warehouse loader;
create schema if not exists radar_airflow;
create table if not exists radar_airflow.radar_archive (
    id string,
    unique_identifier string,
    airline_code string,
    airline_identifier string,
    flight_number string,
    local_departure_date string,
    local_departure_at string,
    local_actual_departure_at string,
    local_arrival_at string,
    local_actual_arrival_at string,
    gmt_departure_at string,
    gmt_actual_departure_at string,
    gmt_arrival_at string,
    gmt_actual_arrival_at string,
    departure_airport_code string,
    arrival_airport_code string,
    departure_status string,
    departure_status_details string,
    arrival_status string,
    arrival_status_details string,
    delay_mins string,
    operating_airline_code string,
    operating_airline_identifier string,
    operating_airline_flight_number string,
    final_status_received string,
    distance_km string,
    seats string,
    utc_variation_arrival_in_minutes string,
    utc_variation_departure_in_minutes string,
    flight_export_id string,
    last_status_update_filename string,
    last_status_update_trans_id string,
    created_from_update string,
    diversion_airport_code string,
    service_type string,
    aircraft_type string,
    aircraft_registration string,
    arrival_scheduled_terminal string,
    arrival_actual_terminal string,
    departure_scheduled_terminal string,
    departure_actual_terminal string,
    arrival_actual_gate string,
    departure_actual_gate string,
    flow string,
    created_at string,
    updated_at string,
    departure_status_category string,
    arrival_status_category string,
    local_estimated_departure_at string,
    local_estimated_arrival_at string,
    gmt_estimated_departure_at string,
    gmt_estimated_arrival_at string
);

copy into radar_airflow.radar_archive
from '@s3_radar_flight_versions_stage_dt_production'
file_format = (format_name = 'csv_dt_production');
